### ISSUE TITLE
How to handle the server side errors?

### ISSUE THREAD

**Issue by gvijaydhanasekaran** [RemnantArcher/ionic-validation-directive#1]
I have a login page. In that page I need to show the server side errors. Like (**The email and password you entered don't match.**). How can i do this .

```
<validation-item errors="{ required: 'This field is required', minlength: 'Usernames must have at least 6 characters' }">
  <label class="item item-input">
    <input type="text" name="username" ng-model="formInfo.username" placeholder="Username" min-length="6" required>
  </label>
</validation-item>
```

In the above code can I set the errors from controller ? 

![login](https://cloud.githubusercontent.com/assets/7327844/13631317/f76c6a50-e609-11e5-948e-b864311adcdf.png)

**Comment by zakton5** [comment]
This directive's purpose is solely to display the errors that are already on the input. I recommend using something like [Angular UI Validate](https://htmlpreview.github.io/?https://github.com/angular-ui/ui-validate/master/demo/index.html), which supports both synchronous and asynchronous validation. You can put methods in your controller and call them that way. Here is the [github page](https://github.com/angular-ui/ui-validate) for it.

If that doesn't work for you, please let me know and I can try to work something else out.

**Comment by gvijaydhanasekaran** [comment]
I have completed the server side validation by using Angular UI Validate and your directive. It is working fine. Thanks..:)

**Comment by zakton5** [comment]
I'm glad it worked out!
